In [3]:
import pandas as pd
from os import chdir
chdir('/Users/jonathanbeaulieu/Downloads/Kickstarter_2018-12-13T03_20_05_701Z')

In [26]:
col = ['backers_count', 'blurb', 'category', 'converted_pledged_amount',
       'country', 'created_at', 'creator', 'currency', 'currency_symbol',
       'currency_trailing_code', 'current_currency', 'deadline', 'fx_rate', 'goal', 'id', 
       'is_starred', 'launched_at', 'location',
       'name', 'pledged', 'spotlight', 'staff_pick', 'state', 'state_changed_at',
       'static_usd_rate', 'usd_pledged', 'usd_type']

filenames = [f"Kickstarter{i:03}.csv" for i in range(1,55)] #aussi possible en legacy ["%03d" % i for i in range(121)]

df = pd.read_csv('Kickstarter.csv', parse_dates=True, usecols=col)

for i in filenames:
    file = pd.read_csv(i, parse_dates=True, usecols=col)
    df = df.append(file)
    
df.shape
df.head()
df.tail()

,backers_count,blurb,category,converted_pledged_amount,country,created_at,creator,currency,currency_symbol,currency_trailing_code,...,location,name,pledged,spotlight,staff_pick,state,state_changed_at,static_usd_rate,usd_pledged,usd_type
1345,25,After 10 years of working and a successful pre...,"{""id"":24,""name"":""Performance Art"",""slug"":""art/...",6511,US,1335216463,"{""id"":845111151,""name"":""Victor de Almeida"",""is...",USD,$,True,...,"{""id"":2442047,""name"":""Los Angeles"",""slug"":""los...",Stravinsky's Rite of Spring for Viola and Piano,6511.0,True,False,successful,1338582259,1.000000,6511.000000,international
1346,181,"La primera aplicación móvil, gratuita y biling...","{""id"":1,""name"":""Art"",""slug"":""art"",""position"":1...",14159,MX,1541625703,"{""id"":985097675,""name"":""Onda MX"",""slug"":""ondam...",MXN,$,True,...,"{""id"":116545,""name"":""Mexico City"",""slug"":""mexi...",Onda MX App: Mexico City art guide & living ar...,285797.8,False,True,live,1542087170,0.049601,14175.956707,international
1347,287,iPhone light accessory for night photography. ...,"{""id"":52,""name"":""Hardware"",""slug"":""technology/...",22407,US,1382718586,"{""id"":1726454615,""name"":""Jedd Goble"",""is_regis...",USD,$,True,...,"{""id"":2487956,""name"":""San Francisco"",""slug"":""s...",Ember – The Night Photography Tool for iPhone,22407.0,False,False,failed,1395502895,1.000000,22407.000000,domestic
1348,94,This is a project that 100% reflects the phras...,"{""id"":37,""name"":""Country & Folk"",""slug"":""music...",10001,US,1412186535,"{""id"":2062939259,""name"":""Conor Clemmons"",""is_r...",USD,$,True,...,"{""id"":2457170,""name"":""Nashville"",""slug"":""nashv...",The Conor Clemmons Debut EP,10001.0,True,False,successful,1416507026,1.000000,10001.000000,domestic
1349,4,Vinyl decorations taken to the next level.\n\n...,"{""id"":27,""name"":""Graphic Design"",""slug"":""desig...",135,US,1383779758,"{""id"":1273870261,""name"":""Javier"",""is_registere...",USD,$,True,...,"{""id"":2415780,""name"":""Guttenberg"",""slug"":""gutt...",Personalized Vinyl Decals,135.0,False,False,failed,1386533026,1.000000,135.000000,international

In [33]:
df['created_at'] = pd.to_datetime(df['created_at'], unit='s')
df['launched_at'] = pd.to_datetime(df['launched_at'], unit='s')
df['state_changed_at'] = pd.to_datetime(df['state_changed_at'], unit='s')
df['deadline'] = pd.to_datetime(df['deadline'], unit='s')

df.head()

,backers_count,blurb,category,converted_pledged_amount,country,created_at,creator,currency,currency_symbol,currency_trailing_code,...,location,name,pledged,spotlight,staff_pick,state,state_changed_at,static_usd_rate,usd_pledged,usd_type
0,170,A documentary about two circuses in remote cor...,"{""id"":30,""name"":""Documentary"",""slug"":""film & v...",27455,US,2012-06-12 18:30:42,"{""id"":1596438170,""name"":""Susan Gray"",""is_regis...",USD,$,True,...,"{""id"":2367105,""name"":""Boston"",""slug"":""boston-m...",Big Top Without Borders,27455.55,True,False,successful,2012-11-18 16:30:31,1.000000,27455.55,international
1,10,A multi-media IPad book telling the true story...,"{""id"":46,""name"":""Children's Books"",""slug"":""pub...",535,US,2012-11-03 11:10:26,"{""id"":529454320,""name"":""Barb Buresh"",""is_regis...",USD,$,True,...,"{""id"":2466256,""name"":""Orlando"",""slug"":""orlando...","The Story of ""Pweep"": From Egg - To Peacock",535.00,True,False,successful,2012-12-19 20:39:06,1.000000,535.00,international
2,0,We are college students that get drunk and the...,"{""id"":357,""name"":""Audio"",""slug"":""journalism/au...",0,CA,2014-11-13 22:20:56,"{""id"":1626740608,""name"":""DC Radio"",""is_registe...",CAD,$,True,...,"{""id"":4118,""name"":""Toronto"",""slug"":""toronto-on...",DC Radio,0.00,False,False,failed,2014-12-18 15:20:15,0.886698,0.00,domestic
3,0,"its Ali bangerz,its time to stand up for other...","{""id"":44,""name"":""World Music"",""slug"":""music/wo...",0,US,2015-11-04 19:18:23,"{""id"":631293879,""name"":""Ali Bangerz"",""is_regis...",USD,$,True,...,"{""id"":2466256,""name"":""Orlando"",""slug"":""orlando...",Ali Bangerz- two New Full Lenght Albums,0.00,False,False,failed,2015-12-05 19:50:00,1.000000,0.00,domestic
4,62,A young neuroscientist attempts to reconnect w...,"{""id"":30,""name"":""Documentary"",""slug"":""film & v...",6705,US,2010-09-09 03:38:56,"{""id"":1385040366,""name"":""Alexis Gambis (delete...",USD,$,True,...,"{""id"":12589335,""name"":""Brooklyn"",""slug"":""brook...",Deja-Vu: Dissecting Memory on Camera,6705.00,True,True,successful,2010-10-16 03:45:24,1.000000,6705.00,international

In [35]:
df.set_index('created_at', inplace=True)
df.head()

,backers_count,blurb,category,converted_pledged_amount,country,creator,currency,currency_symbol,currency_trailing_code,current_currency,...,location,name,pledged,spotlight,staff_pick,state,state_changed_at,static_usd_rate,usd_pledged,usd_type
created_at,,,,,,,,,,,,,,,,,,,,,
2012-06-12 18:30:42,170,A documentary about two circuses in remote cor...,"{""id"":30,""name"":""Documentary"",""slug"":""film & v...",27455,US,"{""id"":1596438170,""name"":""Susan Gray"",""is_regis...",USD,$,True,USD,...,"{""id"":2367105,""name"":""Boston"",""slug"":""boston-m...",Big Top Without Borders,27455.55,True,False,successful,2012-11-18 16:30:31,1.000000,27455.55,international
2012-11-03 11:10:26,10,A multi-media IPad book telling the true story...,"{""id"":46,""name"":""Children's Books"",""slug"":""pub...",535,US,"{""id"":529454320,""name"":""Barb Buresh"",""is_regis...",USD,$,True,USD,...,"{""id"":2466256,""name"":""Orlando"",""slug"":""orlando...","The Story of ""Pweep"": From Egg - To Peacock",535.00,True,False,successful,2012-12-19 20:39:06,1.000000,535.00,international
2014-11-13 22:20:56,0,We are college students that get drunk and the...,"{""id"":357,""name"":""Audio"",""slug"":""journalism/au...",0,CA,"{""id"":1626740608,""name"":""DC Radio"",""is_registe...",CAD,$,True,USD,...,"{""id"":4118,""name"":""Toronto"",""slug"":""toronto-on...",DC Radio,0.00,False,False,failed,2014-12-18 15:20:15,0.886698,0.00,domestic
2015-11-04 19:18:23,0,"its Ali bangerz,its time to stand up for other...","{""id"":44,""name"":""World Music"",""slug"":""music/wo...",0,US,"{""id"":631293879,""name"":""Ali Bangerz"",""is_regis...",USD,$,True,USD,...,"{""id"":2466256,""name"":""Orlando"",""slug"":""orlando...",Ali Bangerz- two New Full Lenght Albums,0.00,False,False,failed,2015-12-05 19:50:00,1.000000,0.00,domestic
2010-09-09 03:38:56,62,A young neuroscientist attempts to reconnect w...,"{""id"":30,""name"":""Documentary"",""slug"":""film & v...",6705,US,"{""id"":1385040366,""name"":""Alexis Gambis (delete...",USD,$,True,USD,...,"{""id"":12589335,""name"":""Brooklyn"",""slug"":""brook...",Deja-Vu: Dissecting Memory on Camera,6705.00,True,True,successful,2010-10-16 03:45:24,1.000000,6705.00,international

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 207227 entries, 2012-06-12 18:30:42 to 2013-11-06 23:15:58
Data columns (total 29 columns):
backers_count               207227 non-null int64
blurb                       207217 non-null object
category                    207227 non-null object
converted_pledged_amount    207227 non-null int64
country                     207227 non-null object
creator                     207227 non-null object
currency                    207227 non-null object
currency_symbol             207227 non-null object
currency_trailing_code      207227 non-null bool
current_currency            207227 non-null object
deadline                    207227 non-null int64
disable_communication       207227 non-null bool
friends                     216 non-null object
fx_rate                     207227 non-null float64
goal                        207227 non-null float64
id                          207227 non-null int64
is_starrable                207227 non-null bool
is_starred                  216 non-null object
launched_at                 207227 non-null datetime64[ns]
location                    205936 non-null object
name                        207226 non-null object
pledged                     207227 non-null float64
spotlight                   207227 non-null bool
staff_pick                  207227 non-null bool
state                       207227 non-null object
state_changed_at            207227 non-null datetime64[ns]
static_usd_rate             207227 non-null float64
usd_pledged                 207227 non-null float64
usd_type                    206807 non-null object
dtypes: bool(5), datetime64[ns](2), float64(5), int64(4), object(13)
memory usage: 40.5+ MB

In [121]:
import json
df_test = pd.read_csv('Kickstarter.csv', parse_dates=True, usecols=col)

# Parse CSV where one of the fields is a nested JSON object, stored as a string
stdf = df_test['category'].apply(json.loads) # Cast les valeurs de 'category' de str à dict
df_cat = pd.DataFrame(stdf.tolist()) # or stdf.apply(pd.Series)

# df.join(df['stats'].apply(json.loads).apply(pd.Series))

df_cat.head(1)

,color,id,name,parent_id,position,slug,urls
0,16734574,30,Documentary,11.0,4,film & video/documentary,{'web': {'discover': 'http://www.kickstarter.c...

In [123]:
df_test = pd.read_csv('Kickstarter.csv', parse_dates=True, usecols=col)
#dic = df_test.iloc[:1,2].values
dic = df_test['category']

#print(dic)
type(dic[0])

str

In [116]:
type(stdf[0])

dict

In [113]:
#id11 = df_cat[df_cat['id'] == 30]

#id11 = df_cat.id == 30
id11 = df_cat[df_cat['id'] == 11]
#id11.count()
id11.head()

Empty DataFrame
Columns: [color, id, name, parent_id, position, slug, urls]
Index: []

In [127]:
chdir('/Users/jonathanbeaulieu/Desktop')
df.to_pickle('KS_df_clean_partiel.zip')